import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const departments = [
  "Education",
  "Health",
  "Sports",
  "Science and Technology",
  "Jagannath",
  "Judicial",
  "GAD",
  "Culture",
  "Transport",
  "Home",
  "Forest",
  "Library",
  "Social Welfare",
  "Sericulture",
  "AIDC",
  "Assam Accord",
  "Others",
  "Skill Development"
];

// export const divisions = [
//   "Guwahati Building Division-I",
//   "Guwahati Building Division-II",
//   "Dispur & Guwahati East Territorial Building Division",
//   "Guwahati Electrical Division",
//   "Guwahati City Division No.-I",
//   "Guwahati City Division No.-II",
//   "Jorhat Building Division",
//   "Jorhat Electrical Division",
//   "Tezpur Building Division",
//   "Tezpur Electrical Division",
//   "Silchar Building Division",
//   "Karimganj Building Division",
//   "Kokrajhar Building Division",
//   "Kokrajhar Electrical Division",
//   "Dibrugarh Building Division",
//   "Tinsukia Building Division",
//   "Nagaon Building Division",
//   "Morigaon Building Division",
//   "Dhemaji Building Division",
//   "Lakhimpur Building Division",
//   "Diphu Building Division",
//   "Haflong Building Division",
//   "Barpeta Building Division",
//   "Goalpara Building Division",
//   "Nalbari Building Division",
//   "Baksa Building Division",
//   "Bongaigaon Building Division",
//   "Chirang Building Division",
//   "Sivasagar Building Division",
//   "Golaghat Building Division",
//   "Sonitpur Building Division",
//   "Biswanath Building Division",
//   "Diphu Building Division",
//   "Hamren Building Division",
//   "Haflong Building Division",
//   "Maibang Building Division",
//   "Karimganj Building Division",
//   "Hailakandi Building Division",
//   "Silchar Building Division",
//   "Lakhipur Building Division",
//   "Tinsukia Building Division",
//   "Doomdooma Building Division",
//   "Hojai Building Division",
//   "Lumding Building Division",
//   "Majuli Building Division",
//   "Garmur Building Division",
//   "Udalguri Building Division",
//   "Tangla Building Division",
//   "Baksa Building Division",
//   "Mushalpur Building Division",
//   "Chirang Building Division",
//   "Kajolgaon Building Division",
//   "Hailakandi Building Division",
//   "Lala Building Division",
//   "Biswanath Building Division",
//   "Gohpur Building Division",
//   "Charaideo Building Division",
//   "Sonari Building Division",
//   "South Salmara Building Division",
//   "Hatsingimari Building Division",
//   "West Karbi Anglong Building Division",
//   "Baithalangso Building Division",
//   "Tamulpur Building Division",
//   "Nagrijuli Building Division",
//   "Bajali Building Division",
//   "Pathsala Building Division",
// ];

// export const districts = [
//   "Baksa",
//   "Barpeta",
//   "Biswanath",
//   "Bongaigaon",
//   "Cachar",
//   "Charaideo",
//   "Chirang",
//   "Darrang",
//   "Dhemaji",
//   "Dhubri",
//   "Dibrugarh",
//   "Dima Hasao",
//   "Goalpara",
//   "Golaghat",
//   "Hailakandi",
//   "Hojai",
//   "Jorhat",
//   "Kamrup",
//   "Kamrup Metropolitan",
//   "Karbi Anglong",
//   "Karimganj",
//   "Kokrajhar",
//   "Lakhimpur",
//   "Majuli",
//   "Morigaon",
//   "Nagaon",
//   "Nalbari",
//   "Sivasagar",
//   "Sonitpur",
//   "South Salmara-Mankachar",
//   "Tinsukia",
//   "Udalguri",
//   "West Karbi Anglong",
//   "Bajali",
//   "Tamulpur",
// ];

// export const lacs = [
//   "Ratabari (SC)",
//   "Patharkandi",
//   "Karimganj North",
//   "Karimganj South",
//   "Badarpur",
//   "Hailakandi",
//   "Katlicherra",
//   "Algapur",
//   "Silchar",
//   "Sonai",
//   "Dholai (SC)",
//   "Udharbond",
//   "Lakhipur",
//   "Barkhola",
//   "Katigorah",
//   "Haflong (ST)",
//   "Bokajan (ST)",
//   "Howraghat (ST)",
//   "Diphu (ST)",
//   "Baithalangso (ST)",
//   "Mankachar",
//   "Salmara South",
//   "Dhubri",
//   "Gauripur",
//   "Golakganj",
//   "Bilasipara West",
//   "Bilasipara East",
//   "Gossaigaon",
//   "Kokrajhar West (ST)",
//   "Kokrajhar East (ST)",
//   "Sidli (ST)",
//   "Bongaigaon",
//   "Bijni",
//   "Abhayapuri North",
//   "Abhayapuri South (SC)",
//   "Dudhnai (ST)",
//   "Goalpara East",
//   "Goalpara West",
//   "Jaleswar",
//   "Sorbhog",
//   "Bhabanipur",
//   "Patacharkuchi",
//   "Barpeta",
//   "Jania",
//   "Baghbor",
//   "Sarukhetri",
//   "Chenga",
//   "Boko (SC)",
//   "Chaygaon",
//   "Palasbari",
//   "Jalukbari",
//   "Dispur",
//   "Gauhati East",
//   "Gauhati West",
//   "Hajo",
//   "Kamalpur",
//   "Rangiya",
//   "Tamulpur",
//   "Nalbari",
//   "Barkhetry",
//   "Dharmapur",
//   "Barama (ST)",
//   "Chapaguri (ST)",
//   "Panery",
//   "Kalaigaon",
//   "Sipajhar",
//   "Mangaldoi (SC)",
//   "Dalgaon",
//   "Udalguri (ST)",
//   "Majbat",
//   "Dhekiajuli",
//   "Barchalla",
//   "Tezpur",
//   "Rangapara",
//   "Sootea",
//   "Biswanath",
//   "Behali",
//   "Gohpur",
//   "Jagiroad (SC)",
//   "Marigaon",
//   "Laharighat",
//   "Raha (SC)",
//   "Dhing",
//   "Batadroba",
//   "Rupohihat",
//   "Nowgong",
//   "Barhampur",
//   "Samaguri",
//   "Kaliabor",
//   "Jamunamukh",
//   "Hojai",
//   "Lumding",
//   "Bokakhat",
//   "Sarupathar",
//   "Golaghat",
//   "Khumtai",
//   "Dergaon (SC)",
//   "Jorhat",
//   "Majuli (ST)",
//   "Titabar",
//   "Mariani",
//   "Teok",
//   "Amguri",
//   "Nazira",
//   "Mahmara",
//   "Sonari",
//   "Thowra",
//   "Sibsagar",
//   "Bihpuria",
//   "Naoboicha",
//   "Lakhimpur",
//   "Dhakuakhana (ST)",
//   "Dhemaji (ST)",
//   "Jonai (ST)",
//   "Moran",
//   "Dibrugarh",
//   "Lahowal",
//   "Duliajan",
//   "Tingkhong",
//   "Naharkatia",
//   "Chabua",
//   "Tinsukia",
//   "Digboi",
//   "Margherita",
//   "Doomdooma",
//   "Sadiya",
// ];

export const consultants = [
  "Rajkhowa's Archi",
  "Neev",
  "Inhouse",
  "Rajkhowas Aarchi",
  "Aesthetic Creation",
  "Designers Plenum",
  "Integra Venture",
  "Barthakur & associates",
  "Barthakur & Associates",
  "Manash Kagti & Associates",
  "Topubratta Dutta, Architect",
  "J N Khataniar",
  "Akar Foundation",
  "Acorn",
  "M/s Pankaj Phukan Associates",
  "Enarch Consultants Pvt. Ltd.",
  "Architects Collaborative",
  "CP &DS ASSOCIATES",
  "SOLUTUS CONSULTING ENGINEERING PVT. LTD",
  "IRCLASS SYSTEMS & SOLUTIONS",
  "MOLETHU PMC PVT. LTD.",
  "JAG DESIGN & PVT. LTD",
  "Perspective",
  "SKYLINE",
  "CP & DS ASSOCIATES",
  "KAA'S H DESIGN",
  "CP & DS associates",
  "Reja Kabul Architect Pvt Ltd",
  "Design Associates Inc",
  "Manas Kagti",
  "Design Associates",
  "Studio Architect",
  "M/s Tripathi & Associates.",
  "M/S Techton Services Pvt Ltd",
  "M/s WAPCOS ltd.",
  "Design Associates/ M/s Civil Experts Consultants & Testing Centre",
  "Manas Kagti & Associates",
  "Bereau Veritas India Pvt Ltd",
  "K's design cell",
  "Emergent Practises",
  "K's Design cell.",
  "Debajit Sarma",
];

export const contractors = [
  "Sunrise Enterprise.",
  "Kushan Choudhury",
  "Pooja Associates (Contract Division)",
  "Sri Santanu Chakraborty",
  "Abdul Quddus",
  "FTTC Project Private Ltd.",
  "Shree Gautam Construction Co. Ltd.",
  "Manabjyoti Gogoi & Co.",
  "Ganapati Construction Co.",
  "SHIVAAY INFRATECH LLP.",
  "Sunwin Energy and Infra Private Ltd.",
  "Manoj Kumar Sarmah",
  "Sunrise Enterprise",
  "AVR Infraspace Pvt. Ltd.",
  "Om Construction Shambhavi Pvt. Ltd.",
  "Sri Abdul Bachit",
  "Abdul Bachit",
  "M. P. Agarwalla",
  "Power Tools & Engineering",
  "M/s North East Plantations & Commercial Pvt. Ltd",
  "M/S Punjab Engineering Company",
  "M/s North East Plantations & Commercial Pvt. Ltd.",
  "M/s R. D. Construction",
  "M/s N.Bhattacharjee & Associates",
  "M/S Raj Shekhar Construction Pvt. Ltd",
  "M/S Mayur Associates",
  "Pranab Kr. Das",
  "Saidur Rahman",
  "Shri Mrigen Sutradhar",
  "M/S Versha Technotrade Pvt. Ltd.",
  "T & T Projects Ltd",
  "Jatindra Nr. Das",
  "Sri Bajrang Bhadani",
  "Sri Rumesh Kr. Jajodia",
  "Dinabandhu Das",
  "Bilin Adhikary",
  "Mrigen Suttradhar",
  "M/S M.P.Khaitan",
  "Anil Das",
  "M/S Rajshekhar Constn. Pvt. Ltd.",
  "Ganapati Construction Company",
  "M/S Dhunu Construction",
  "Anand Buildtech Pvt Ltd",
  "Ganpati Construction Company",
  "M/S Om Construction",
  "Tribeni Construction Ltd",
  "Versha Technotrade Pvt. Ltd",
  "Ganpati Construction Company Ltd.",
  "Nipul Kalita",
  "Oriental Engineers",
  "JC Construction Pvt. Ltd.",
  "M/s Rank Project & Dev. Pvt.Ltd.",
  "S.K. Integrated Consultants",
  "Bhartia Infra Projects Ltd.",
  "NCC Ltd",
  "Art-E-Mide",
  "M/s Oriental Engineers",
  "FTTC Projects Pvt. Ltd.",
  "OM Constructions",
  "Ahluwalia Contracts (India) Limited",
  "Dinesh Chandra R Agarwal",
  "M/s M.V.V. Satyanarayana",
  "O.P Garodia",
  "M/s Pushpdeep Infrastructure Pvt. Ltd.",
  "UCN Construction Co. Pvt. Ltd.",
  "Honsing Timung",
  "M/S Pooja Associates (Contract Divn)",
  "Punjab Engineering Company",
  "Uday Phukan",
  "O P Garodia",
  "M/S pooja Associates",
  "Tribeni Construction Ltd.",
  "BN Garodia",
];

export const fieldGroups = [
  {
    id: "basic",
    title: "Basic Information",
    description: "Enter the fundamental details about the project",
    fields: [
      {
        name: "projectName",
        label: "Name of Project",
        type: "text",
        required: true,
        help: "Enter the official name of the project as per documents",
      },
      {
        name: "nodalDepartment",
        label: "Name of Nodal Department",
        type: "text",
        required: true,
        help: "The primary department responsible for this project",
      },
      {
        name: "division",
        label: "Name of Division",
        type: "text",
        required: true,
        help: "Administrative division managing the project",
      },
      {
        name: "district",
        label: "Name of District",
        type: "text",
        required: true,
        help: "District where the project is located",
      },
      {
        name: "lac",
        label: "Name of LAC",
        type: "text",
        required: false,
        help: "Legislative Assembly Constituency",
      },
      {
        name: "branch",
        label: "Branch",
        type: "text",
        required: false,
        help: "Branch office responsible (if applicable)",
      },
    ],
  },
  {
    id: "financial",
    title: "Financial Details",
    description: "Enter financial information about the project",
    fields: [
      {
        name: "fundSource",
        label: "Source of Fund",
        type: "text",
        required: true,
        help: "Funding source or scheme name",
      },
      {
        name: "aaNo",
        label: "AA No.",
        type: "text",
        required: true,
        help: "Administrative Approval Number",
      },
      {
        name: "estimatedValue",
        label: "Estimated Value in Cr.",
        type: "number",
        step: "0.01",
        required: true,
        help: "Total project value in Crores",
      },
      {
        name: "financialProgress",
        label: "Financial Progress in Percentage",
        type: "number",
        min: "0",
        max: "100",
        required: false,
        help: "Current financial utilization as percentage",
      },
    ],
  },
  {
    id: "execution",
    title: "Execution Details",
    description: "Enter details about project execution and contractors",
    fields: [
      {
        name: "pmcWorkOrderDate",
        label: "Work Order Date (PMC / Consultancy)",
        type: "date",
        required: false,
        help: "Date when PMC work order was issued",
      },
      {
        name: "worksWorkOrderDate",
        label: "Work Order Date (works)",
        type: "date",
        required: true,
        help: "Date when main works order was issued",
      },
      {
        name: "consultantName",
        label: "Name of Consultant/ PMC",
        type: "text",
        required: false,
        help: "Name of the project management consultant",
      },
      {
        name: "contractorName",
        label: "Name of Contractor",
        type: "text",
        required: true,
        help: "Name of the primary contractor",
      },
      {
        name: "physicalProgress",
        label: "Physical Progress in Percentage",
        type: "number",
        min: "0",
        max: "100",
        required: false,
        help: "Current physical progress as percentage",
      },
    ],
  },
  {
    id: "timeline",
    title: "Timeline & Status",
    description: "Enter project timeline and current status information",
    fields: [
      {
        name: "completionDatePerTender",
        label: "Date of Completion as per Tender",
        type: "date",
        required: true,
        help: "Contract completion date as per tender agreement",
      },
      {
        name: "expectedCompletionDate",
        label: "Expected Date of Completion",
        type: "date",
        required: false,
        help: "Realistic expected date of completion",
      },
      {
        name: "provisions",
        label: "Provisions",
        type: "text",
        required: false,
        help: "Any special provisions for this project",
      },
      {
        name: "landStatus",
        label: "Land Status",
        type: "text",
        required: false,
        help: "Current status of land acquisition (if applicable)",
      },
      {
        name: "remarks",
        label: "Remarks",
        type: "textarea",
        required: false,
        help: "Any additional notes or observations",
      },
    ],
  },
];

export const divisions = [
  "Dispur, Dimoria & Estate Office Territorial Building Division",
  "Haflongnj District Territorial Building Division",
  "Hailakandi District Territorial Building Division",
  "Udharbond, Lakhipur, Barkhola & Katigora Territorial Building Division",
  "Baithalangso Territorial Building Division",
  "Udalguri District & Baksa District Territorial Building Division",
  "Bongaigaon District Territorial Building Division",
  "Bajali District Territorial Building Division",
  "Barpeta District Territorial Building Division",
  "Darrang District Territorial Building Division",
  "Biswanath District Territorial Building Division",
  "Dhemaji(ST) District Territorial Building Division",
  "Majuli(ST) District Territorial Building Division",
  "Morigaon District Territorial Building Division",
  "Kaliabor & Barhampur Territorial Building Division",
  "Hojai District Territorial Building Division",
  "Golaghat District Territorial Building Division",
  "Charaideo District Territorial Building Division",
  "Naharkatia & Duliajan Territorial Building Division",
  "Tinsukia District Territorial Building Division",
  "South Kamrup Territorial Building Division",
  "North Kamrup Territorial Building Division",
  "Nalbari District Territorial Building Division",
  "Dhubri District Territorial Building Division",
  "Estate Office, PWD Dispur",
  "Goalpara & South Salmara District Territorial Building Division",
  "Kokrajhar District & Chirang District Territorial Building Division",
  "Medical College & Hospitals Construction Division",
  "Jalukbari, Guwahati Central & New Guwahati Territorial Building Division",
  "Nagaon-Batadrava, Raha(SC), Dhing, Rupohihat & Samaguri Territorial Building Division",
  "Assam House Construction Division",
  "Guwahati Elect. Division",
  "Jorhat Elect. Division",
  "Kokrajhar Elect. Division",
  "Tezpur Elect. Division",
  "Diphu Elect. Division",
  "Sonitpur District Territorial Building Division",
  "Lakhimpur District Territorial Building Division",
  "Silchar, Sonai & Dholai Territorial Building Division",
  "Jorhat District Territorial Building Division",
  "Sivasagar District Territorial Building Division",
  "Dibrugarh, Chabua-Lahowal, Khowang & Tingkhong Territorial Building Division",
  "Karbi Anglong District Territorial Building Division",
  "Haflong Territorial Building Division",
];

export const districts = [
  "Kokrajhar (ST)",
  "Dhubri",
  "Barpeta",
  "Darrang-Udalguri",
  "Guwahati",
  "Diphu (ST)",
  "Karimganj",
  "Silchar (SC)",
  "Nagaon",
  "Kaziranga",
  "Sonitpur",
  "Lakhimpur",
  "Dibrugarh",
  "Jorhat",
];

export const lacs = [
  "Gossaigaon",
  "Dotma (ST)",
  "Kokrajhar (ST)",
  "Baokhungri",
  "Parbatjhora",
  "Sidli Chirang (ST)",
  "Bijni",
  "Manas",
  "Baksa (ST)",
  "Golakganj",
  "Gauripur",
  "Dhubri",
  "Birsing-Jarua",
  "Bilasipara",
  "Mankachar",
  "Jaleswar",
  "Goalpara East",
  "Srijangram",
  "Mandia",
  "Chenga",
  "Abhayapuri",
  "Bongaigaon",
  "Bhawanipur-Sorbhog",
  "Barpeta (SC)",
  "Pakabetbari",
  "Bajali",
  "Hajo-Sualkuchi (SC)",
  "Barkhetri",
  "Nalbari",
  "Tihu",
  "Rangia",
  "Kamalpur",
  "Tamulpur (ST)",
  "Goreswar",
  "Bhergaon",
  "Udalguri (ST)",
  "Mazbat",
  "Tangla",
  "Sipajhar",
  "Mangaldai",
  "Dalgaon",
  "Goalpara West (ST)",
  "Dudhnoi (ST)",
  "Chamaria",
  "Boko-Chaygaon (ST)",
  "Palasbari",
  "Dispur",
  "Dimoria (SC)",
  "New Guwahati",
  "Guwahati Central",
  "Jalukbari",
  "Bokajan (ST)",
  "Howraghat (ST)",
  "Diphu (ST)",
  "Rongkhang (ST)",
  "Amri (ST)",
  "Haflong (ST)",
  "Hailakandi",
  "Algapur-Katlicherra",
  "Karimganj North",
  "Karimganj South",
  "Patharkandi",
  "Ram Krishna Nagar (SC)",
  "Lakhipur",
  "Udharbond",
  "Katigorah",
  "Borkhola",
  "Silchar",
  "Sonai",
  "Dholai (SC)",
  "Jagiroad (SC)",
  "Laharighat",
  "Morigaon",
  "Dhing",
  "Rupahihat",
  "Samaguri",
  "Nagaon-Batadraba",
  "Raha (SC)",
  "Kaliabor",
  "Barhampur",
  "Binnakandi",
  "Hojai",
  "Lumding",
  "Golaghat",
  "Dergaon",
  "Khumtai",
  "Bokakhat",
  "Sarupathar",
  "Dhekiajuli",
  "Barchalla",
  "Tezpur",
  "Rangapara",
  "Naduar",
  "Biswanath",
  "Behali (SC)",
  "Gohpur",
  "Bihpuria",
  "Ranganadi",
  "Nowboicha (SC)",
  "Lakhimpur",
  "Dhakuakhana (ST)",
  "Dhemaji (ST)",
  "Sissiborgaon",
  "Jonai (ST)",
  "Sadiya",
  "Doom Dooma",
  "Margherita",
  "Digboi",
  "Makum",
  "Tinsukia",
  "Chabua-Lahowal",
  "Dibrugarh",
  "Khowang",
  "Duliajan",
  "Tingkhong",
  "Naharkatia",
  "Sonari",
  "Mahmora",
  "Demow",
  "Sibsagar",
  "Nazira",
  "Majuli (ST)",
  "Teok",
  "Jorhat",
  "Mariani",
  "Titabor",
];
